apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Base ArgoCD installation
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# Patch ArgoCD ConfigMap to enable kustomize plugins and repo server for KSOPS
patches:
  - path: ./resources/argocd-cm-patch.yaml
  - path: ./resources/repo-server-patch.yaml
